name: GitHub Stats Generator

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate GitHub Stats SVG
        uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: anshc022
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_lines: yes
          plugin_traffic: yes
          plugin_followup: yes
          plugin_repositories: yes
          plugin_repositories_featured: anshc022/TrackMine, anshc022/anshc022
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "📊 Update GitHub metrics" && git push)
