name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday at midnight (less frequent)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Update README timestamp
        run: |
          echo "⏰ Updating profile timestamp..."
          
          # Update the "Last updated" line in README if it exists
          if grep -q "Last updated:" README.md; then
            sed -i "s/Last updated: .*/Last updated: $(date +'%B %Y') - Always evolving!* ⚡/" README.md
            echo "✅ Updated timestamp in README"
          else
            echo "ℹ️ No timestamp found to update"
          fi
          
      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update recent activity'
          MAX_LINES: 5
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update profile README" && git push)
